language: android
sudo: true
env:
  global:
    - ANDROID_ABI=arm64-v8a
    - ANDROID_EMU_API_LEVEL=25

android:
  components:
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by the project
    - build-tools-26.0.2
    # The SDK version used to compile the project
    - android-25
    # System image that is gonna be used.
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL

before_script:
  - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_apis/$ANDROID_ABI
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew build connectedAndroidTest